minimumReleaseAge: 4320
minimumReleaseAgeExclude:
  - "@opencode-ai/sdk"

packages:
  - "apps/*"
  - "packages/*"
  - "ee/apps/*"
  - "ee/packages/*"

catalog:
  react: 19.2.4
  react-dom: 19.2.4

catalogs:
  react18:
    react: 18.2.0
    react-dom: 18.2.0
linkWorkspacePackages: true
preferWorkspacePackages: true
allowBuilds:
  "@sentry/cli": true
  "@whiskeysockets/baileys": true
  better-sqlite3: true
  electron: true
  electron-winstaller: true
  esbuild: true
  msw: false
  node-pty: true
  protobufjs: true
  sharp: true
patchedDependencies:
  '@better-auth/drizzle-adapter@1.6.11': patches/@better-auth__drizzle-adapter@1.6.11.patch
  '@better-auth/oauth-provider@1.6.11': patches/@better-auth__oauth-provider@1.6.11.patch
  '@modelcontextprotocol/sdk': patches/@modelcontextprotocol__sdk.patch
