name: Bug report
description: Report a problem in OpenWork
title: "[Bug]: "
labels:
  - bug
body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: What's not working / wrong?
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: To Reproduce
      description: "Minimal Steps to reproduce the issue:"
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: A short description of what you expected to happen.
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
      description: A short description of what actually happened.
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots (optional)
      description: If applicable, add screenshots or a video to help explain your problem.
    validations:
      required: false
  - type: textarea
    id: desktop_info
    attributes:
      label: OW version & Desktop info (optional) 
      description: |
        Include OS and OpenWork version if possible.
        OpenWork version: Settings > General.
      placeholder: |
        - OpenWork version: [e.g. 0.1.166]
        - OS: [e.g. macOS Tahoe 26.2]
    validations:
      required: false
  - type: textarea
    id: additional_context
    attributes:
      label: Additional context (optional)
      description: Add any other context about the problem here.
    validations:
      required: false
