CREATE TABLE IF NOT EXISTS `apikey` (
  `id` varchar(64) NOT NULL,
  `config_id` varchar(255) NOT NULL DEFAULT 'default',
  `name` varchar(255) DEFAULT NULL,
  `start` varchar(32) DEFAULT NULL,
  `prefix` varchar(255) DEFAULT NULL,
  `key` varchar(255) NOT NULL,
  `reference_id` varchar(64) NOT NULL,
  `refill_interval` bigint DEFAULT NULL,
  `refill_amount` int DEFAULT NULL,
  `last_refill_at` timestamp(3) NULL,
  `enabled` boolean NOT NULL DEFAULT true,
  `rate_limit_enabled` boolean NOT NULL DEFAULT true,
  `rate_limit_time_window` bigint DEFAULT NULL,
  `rate_limit_max` int DEFAULT NULL,
  `request_count` int DEFAULT 0,
  `remaining` int DEFAULT NULL,
  `last_request` timestamp(3) NULL,
  `expires_at` timestamp(3) NULL,
  `created_at` timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `permissions` text,
  `metadata` text,
  CONSTRAINT `apikey_id` PRIMARY KEY (`id`),
  KEY `apikey_config_id` (`config_id`),
  KEY `apikey_reference_id` (`reference_id`),
  KEY `apikey_key` (`key`)
);
