DROP INDEX `desktop_policy_member_policy_id` ON `desktop_policy_member`;--> statement-breakpoint
DROP INDEX `desktop_policy_organization_id` ON `desktop_policy`;--> statement-breakpoint
DROP INDEX `inference_org_limit_policies_organization_id` ON `inference_org_limit_policies`;--> statement-breakpoint
DROP INDEX `inference_org_upstream_provider_keys_organization_id` ON `inference_org_upstream_provider_keys`;--> statement-breakpoint
DROP INDEX `inference_org_usage_buckets_policy_id` ON `inference_org_usage_buckets`;--> statement-breakpoint
DROP INDEX `member_organization_id` ON `member`;--> statement-breakpoint
DROP INDEX `organization_brand_asset_organization_id` ON `organization_brand_asset`;--> statement-breakpoint
DROP INDEX `organization_role_organization_id` ON `organization_role`;--> statement-breakpoint
DROP INDEX `scim_group_provider_id` ON `scim_group`;--> statement-breakpoint
DROP INDEX `connected_account_org_membership_id` ON `connected_account`;--> statement-breakpoint
DROP INDEX `org_oauth_client_organization_id` ON `org_oauth_client`;--> statement-breakpoint
DROP INDEX `plugin_mcp_req_binding_organization_id` ON `plugin_mcp_requirement_binding`;--> statement-breakpoint
DROP INDEX `llm_provider_access_llm_provider_id` ON `llm_provider_access`;--> statement-breakpoint
DROP INDEX `llm_provider_model_llm_provider_id` ON `llm_provider_model`;--> statement-breakpoint
DROP INDEX `config_object_access_grant_config_object_id` ON `config_object_access_grant`;--> statement-breakpoint
DROP INDEX `config_object_version_config_object_id` ON `config_object_version`;--> statement-breakpoint
DROP INDEX `connector_account_organization_id` ON `connector_account`;--> statement-breakpoint
DROP INDEX `connector_instance_access_grant_instance_id` ON `connector_instance_access_grant`;--> statement-breakpoint
DROP INDEX `connector_instance_organization_id` ON `connector_instance`;--> statement-breakpoint
DROP INDEX `connector_mapping_connector_target_id` ON `connector_mapping`;--> statement-breakpoint
DROP INDEX `connector_source_binding_config_object_id` ON `connector_source_binding`;--> statement-breakpoint
DROP INDEX `connector_target_connector_instance_id` ON `connector_target`;--> statement-breakpoint
DROP INDEX `marketplace_access_grant_marketplace_id` ON `marketplace_access_grant`;--> statement-breakpoint
DROP INDEX `marketplace_plugin_marketplace_id` ON `marketplace_plugin`;--> statement-breakpoint
DROP INDEX `plugin_access_grant_plugin_id` ON `plugin_access_grant`;--> statement-breakpoint
DROP INDEX `plugin_config_object_plugin_id` ON `plugin_config_object`;--> statement-breakpoint
DROP INDEX `org_subscriptions_organization_id` ON `org_subscriptions`;--> statement-breakpoint
DROP INDEX `team_member_team_id` ON `team_member`;--> statement-breakpoint
DROP INDEX `team_organization_id` ON `team`;--> statement-breakpoint
CREATE INDEX `idx_connector_account_on_remote_id` ON `connector_account` (`remote_id`);